name: Project CICD flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zodape2001/docker-githubaction-springboot
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile.ci
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
